# Generated by Django 4.1.4 on 2023-01-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Popular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("image", models.ImageField(upload_to="images/")),
                ("price", models.FloatField()),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Populars",
            },
        ),
    ]
