# Generated by Django 4.1.4 on 2023-01-02 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_popular"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="popular",
            name="price",
        ),
    ]
